<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EFCore/**/*.cs;Northwind.Models/**/*.cs" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />

    <PackageReference Version="10.0.12 " Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
    <ProjectReference Include="Northwind.Models/Northwind.Models.csproj" />
  </ItemGroup>

</Project>
